// Marcas y modelos populares en el mercado colombiano
export const MARCAS_MODELOS = {
  'Chevrolet': ['Spark', 'Sail', 'Beat', 'Onix', 'Tracker', 'Captiva', 'Equinox', 'Traverse', 'Trax', 'Orlando', 'Cruze', 'Aveo', 'Optra', 'Sonic', 'N300', 'N400', 'NHR', 'NKR', 'NPR', 'Silverado', 'Colorado', 'D-Max', 'Luv'],
  'Renault': ['Kwid', 'Sandero', 'Stepway', 'Logan', 'Duster', 'Koleos', 'Captur', 'Oroch', 'Alaskan', 'Kangoo', 'Master', 'Clio', 'Symbol', 'Megane', 'Fluence', 'Scala'],
  'Mazda': ['2', '3', '6', 'CX-3', 'CX-30', 'CX-5', 'CX-50', 'CX-9', 'MX-5', 'BT-50'],
  'Toyota': ['Corolla', 'Yaris', 'Hilux', 'Fortuner', 'Prado', 'Land Cruiser', 'RAV4', 'Rush', 'Camry', 'Hiace', 'Hino', '4Runner', 'Tacoma', 'Tundra', 'Supra', 'C-HR'],
  'Kia': ['Picanto', 'Rio', 'Cerato', 'Forte', 'K5', 'Sportage', 'Seltos', 'Sorento', 'Carnival', 'Soul', 'Stinger', 'EV6', 'Niro', 'Stonic'],
  'Hyundai': ['Grand i10', 'i20', 'Accent', 'Elantra', 'Sonata', 'Tucson', 'Santa Fe', 'Creta', 'Venue', 'Kona', 'Palisade', 'Ioniq', 'Porter', 'HD65', 'HD78', 'Starex'],
  'Nissan': ['March', 'Versa', 'Sentra', 'Kicks', 'Qashqai', 'X-Trail', 'Pathfinder', 'Frontier', 'NP300', 'Navara', 'Murano', 'Juke', 'Note', 'Leaf', 'Titan'],
  'Ford': ['Fiesta', 'Focus', 'Fusion', 'Escape', 'Explorer', 'Expedition', 'Ranger', 'F-150', 'Bronco', 'Maverick', 'Territory', 'Edge', 'EcoSport', 'Transit'],
  'Volkswagen': ['Gol', 'Polo', 'Virtus', 'Jetta', 'Passat', 'Golf', 'Tiguan', 'T-Cross', 'Taos', 'Touareg', 'Amarok', 'Saveiro', 'Crafter', 'Transporter'],
  'Suzuki': ['Alto', 'Celerio', 'Swift', 'Baleno', 'Ciaz', 'Vitara', 'Grand Vitara', 'Jimny', 'S-Cross', 'Ertiga', 'XL7', 'Carry'],
  'Honda': ['Brio', 'City', 'Civic', 'Accord', 'CR-V', 'HR-V', 'WR-V', 'Pilot', 'Fit', 'Jazz', 'Ridgeline'],
  'Mitsubishi': ['Mirage', 'Lancer', 'Outlander', 'Eclipse Cross', 'ASX', 'Montero Sport', 'Pajero', 'L200', 'Canter'],
  'Subaru': ['Impreza', 'Legacy', 'Outback', 'Forester', 'XV', 'Crosstrek', 'WRX', 'BRZ', 'Ascent'],
  'BMW': ['Serie 1', 'Serie 2', 'Serie 3', 'Serie 4', 'Serie 5', 'Serie 7', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4', 'i4', 'iX'],
  'Mercedes-Benz': ['Clase A', 'Clase B', 'Clase C', 'Clase E', 'Clase S', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'AMG GT', 'Sprinter', 'Vito'],
  'Audi': ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'e-tron', 'TT', 'RS'],
  'Peugeot': ['208', '301', '308', '2008', '3008', '5008', 'Partner', 'Expert', 'Boxer', 'Rifter'],
  'Citroen': ['C3', 'C4', 'C5 Aircross', 'Berlingo', 'Jumpy', 'Jumper', 'C-Elysee'],
  'Fiat': ['500', 'Argo', 'Cronos', 'Mobi', 'Toro', 'Ducato', 'Fiorino', 'Strada', 'Pulse'],
  'Jeep': ['Renegade', 'Compass', 'Cherokee', 'Grand Cherokee', 'Wrangler', 'Gladiator'],
  'Dodge': ['Journey', 'Durango', 'Charger', 'Challenger', 'Ram 1500', 'Ram 2500'],
  'Chery': ['QQ', 'Tiggo 2', 'Tiggo 3', 'Tiggo 4', 'Tiggo 5X', 'Tiggo 7', 'Tiggo 8', 'Arrizo 5'],
  'JAC': ['S1', 'S2', 'S3', 'S4', 'S7', 'J4', 'Refine', 'X200', 'Sunray'],
  'Great Wall': ['Haval H2', 'Haval H6', 'Haval Jolion', 'Haval Dargo', 'Wingle 5', 'Wingle 7', 'Poer'],
  'BAIC': ['X25', 'X35', 'X55', 'X65', 'D20', 'Senova'],
  'Foton': ['Tunland', 'Toano', 'Gratour', 'Aumark'],
  'DFSK': ['Glory 330', 'Glory 560', 'Glory 580', 'K01', 'K02', 'C35', 'C37'],
  'MG': ['ZS', 'HS', 'RX5', 'GT', 'Marvel R', '5', '3'],
  'Volvo': ['S40', 'S60', 'S90', 'V40', 'V60', 'XC40', 'XC60', 'XC90'],
  'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Sport', 'Range Rover Evoque', 'Range Rover Velar'],
  'Porsche': ['Cayenne', 'Macan', 'Panamera', '911', 'Taycan', '718 Cayman', '718 Boxster'],
  'Mini': ['Cooper', 'Countryman', 'Clubman'],
  'Lexus': ['IS', 'ES', 'RX', 'NX', 'UX', 'GX', 'LX', 'LC'],
  'Isuzu': ['D-Max', 'MU-X', 'NHR', 'NKR', 'NPR', 'NQR', 'FRR'],
  'Hino': ['300', '500', '700', 'Dutro'],
  'Freightliner': ['M2', 'Cascadia', '108SD', '114SD'],
  'Internacional': ['DuraStar', 'WorkStar', 'ProStar', 'LoneStar'],
}

export const MARCAS = Object.keys(MARCAS_MODELOS).sort()

export function getModelos(marca) {
  return MARCAS_MODELOS[marca] || []
}

// Items de inspeccion digital vehicular (DVI)
export const INSPECCION_CATEGORIAS = [
  {
    nombre: 'Frenos',
    items: [
      'Pastillas de freno delanteras',
      'Pastillas de freno traseras',
      'Discos de freno delanteros',
      'Discos de freno traseros',
      'Freno de estacionamiento',
      'Mangueras y lineas de freno',
      'Nivel de liquido de frenos',
    ],
  },
  {
    nombre: 'Suspension y Direccion',
    items: [
      'Amortiguadores delanteros',
      'Amortiguadores traseros',
      'Resortes / espirales',
      'Terminales de direccion',
      'Rotulas',
      'Bujes de suspension',
      'Barra estabilizadora',
      'Cremallera de direccion',
    ],
  },
  {
    nombre: 'Llantas',
    items: [
      'Estado de llantas delanteras (labrado)',
      'Estado de llantas traseras (labrado)',
      'Presion de inflado',
      'Llanta de repuesto',
      'Rines y tuercas',
    ],
  },
  {
    nombre: 'Exterior del Vehiculo',
    items: [
      'Estado de la carroceria',
      'Luces delanteras',
      'Luces traseras',
      'Direccionales y exploradoras',
      'Limpiaparabrisas y liquido',
      'Vidrios y parabrisas',
      'Estado de los espejos',
      'Pestillo del capo',
    ],
  },
  {
    nombre: 'Motor',
    items: [
      'Aceite motor (nivel y estado)',
      'Filtro de aceite',
      'Filtro de aire motor',
      'Nivel de refrigerante',
      'Nivel de liquido de embrague',
      'Nivel del electrolito de la bateria',
      'Estado de correas de accesorios',
      'Fugas en tuberias y mangueras',
      'Sistema de refrigeracion',
      'Aceite transmision automatica',
      'Limpiador sistema combustible',
    ],
  },
  {
    nombre: 'Interior',
    items: [
      'Lista de chequeo del tecnico',
      'Revision de luces tablero',
      'Testigos de falla',
      'Estado del aire acondicionado',
      'Estado del sistema electrico',
      'Cinturones de seguridad',
      'Extintor (fecha de vencimiento)',
      'Botiquin y kit de carretera',
    ],
  },
  {
    nombre: 'Recomendaciones',
    items: [
      'Alineacion y balanceo',
      'Rotacion de llantas',
      'Cambio de aceite',
      'Programacion de mantenimiento',
    ],
  },
]

// Precios referencia mano de obra (Colombia 2026, pesos)
export const PRECIOS_MANO_OBRA = [
  { servicio: 'Cambio de aceite y filtro', precioMin: 40000, precioMax: 80000 },
  { servicio: 'Cambio de pastillas de freno', precioMin: 60000, precioMax: 120000 },
  { servicio: 'Cambio de discos de freno', precioMin: 80000, precioMax: 150000 },
  { servicio: 'Cambio de correa de distribucion', precioMin: 200000, precioMax: 450000 },
  { servicio: 'Alineacion y balanceo', precioMin: 50000, precioMax: 90000 },
  { servicio: 'Cambio de amortiguadores (par)', precioMin: 100000, precioMax: 200000 },
  { servicio: 'Cambio de bujias', precioMin: 40000, precioMax: 100000 },
  { servicio: 'Diagnostico computarizado', precioMin: 50000, precioMax: 100000 },
  { servicio: 'Cambio de bateria', precioMin: 20000, precioMax: 40000 },
  { servicio: 'Reparacion de A/C (recarga gas)', precioMin: 80000, precioMax: 180000 },
  { servicio: 'Cambio de filtro de aire', precioMin: 15000, precioMax: 30000 },
  { servicio: 'Cambio de liquido de frenos', precioMin: 30000, precioMax: 60000 },
  { servicio: 'Cambio de refrigerante', precioMin: 40000, precioMax: 80000 },
  { servicio: 'Reparacion de suspension', precioMin: 120000, precioMax: 300000 },
  { servicio: 'Cambio de embrague', precioMin: 300000, precioMax: 600000 },
  { servicio: 'Reparacion caja de velocidades', precioMin: 400000, precioMax: 1200000 },
  { servicio: 'Scanner / lectura de codigos', precioMin: 30000, precioMax: 60000 },
  { servicio: 'Limpieza de inyectores', precioMin: 80000, precioMax: 150000 },
  { servicio: 'Sincronizacion motor', precioMin: 60000, precioMax: 120000 },
  { servicio: 'Latoneria y pintura (panel)', precioMin: 150000, precioMax: 500000 },
  { servicio: 'Cambio de aceite transmision', precioMin: 60000, precioMax: 120000 },
  { servicio: 'Revision pre-tecnicomecanica', precioMin: 40000, precioMax: 80000 },
  { servicio: 'Cambio de correas accesorios', precioMin: 60000, precioMax: 120000 },
  { servicio: 'Reparacion motor de arranque', precioMin: 80000, precioMax: 200000 },
  { servicio: 'Reparacion alternador', precioMin: 80000, precioMax: 200000 },
]
